### ISSUE TITLE
test rigged simplified button

### ISSUE THREAD

**Issue by dmjezewska** [alloverse/open-planning#118]

**Comment by dmjezewska** [comment]
https://drive.google.com/file/d/15oWQBHg7sQsBt_FMDQYcLFUDirEsoMoT/view

**Comment by nevyn** [comment]
depends on: https://github.com/alloverse/allovisor/issues/40

**Comment by nevyn** [comment]
https://drive.google.com/file/d/16-iewXrspM9GU4PtfOea6vB9sC1yVI6N/view

**Comment by nevyn** [comment]
![image](https://user-images.githubusercontent.com/34791/179351944-c8dd6525-855e-4bc0-83dc-391fe514bd66.png)


still  figuring out rotations

**Comment by nevyn** [comment]
@dmjezewska:

* With our coordinate space specification, front/back are reversed in this example: "left" should be "right", and "front" should be "back" (and vice versa).
* When moving what is now called "front", one vertex of "back" also moves; it seems the weight for the pair of "front" bone and "some vertex of back plane" is higher than zero
* Due to weights not being 100% perfect, if I move more than one bone, the whole model becomes a little bit skewed

![image](https://user-images.githubusercontent.com/34791/179352220-e94362d7-6791-468c-9043-889158b1f437.png)

**Comment by nevyn** [comment]
https://user-images.githubusercontent.com/34791/179352908-264d2dd6-b497-4ff3-bc1a-f7997e33ce86.mp4
